version: '3.3'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatapp
    restart: always
    networks:
      - "chat-network"
    volumes:
      - "chat-volume:/var/lib/mysql"

  backend:
    build:
      context: ./backend
    container_name: chat-backend
    ports:
      - "5000:5000"
    networks:
      - "chat-network"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chatapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always
    depends_on: 
      - db

  frontend:
    build:
      context: ./frontend
    container_name: chat-frontend
    ports:
      - "8081:80"
    networks:
      - "chat-network"
    restart: always
    depends_on: 
      - backend

volumes:
  chat-volume:

networks:
  chat-network:
   




 

